exports.MESSAGE_JOIN = 0;
exports.MESSAGE_JOIN_ERROR = 1;
exports.MESSAGE_NEW_USER = 2;
exports.MESSAGE_CHANGE_ROOM = 3;
exports.MESSAGE_CHANGE_ROOM_ERROR = 4;
exports.MESSAGE_USER_CHANGED_ROOM = 5;
exports.MESSAGE_MASTER = 6;
exports.MESSAGE_USER_LEFT = 7;
exports.MESSAGE_DATA_OBJECT_UPDATE = 8;
exports.MESSAGE_DATA_OBJECT_DELETE = 9;
exports.MESSAGE_DATA_OBJECT_CREATED = 10;
exports.MESSAGE_INIT_DATA_OBJECT = 18;

exports.MESSAGE_GET_SESSION_LIST = 11;
exports.MESSAGE_GET_ROOM_LIST = 12;
exports.MESSAGE_GET_USER_LIST = 13;
exports.MESSAGE_CHAT_MESSAGE = 14;
exports.MESSAGE_CUSTOM_MESSAGE = 15;

exports.MESSAGE_PING = 16;

exports.MESSAGE_DATA_OBJECTS_SENT = 17;

exports.UPDATE_POLICY_PRIVATE = 0;
exports.UPDATE_POLICY_PUPLIC = 1;



exports.ERROR_SERVER_FULL = 0;
exports.ERROR_ROOM_FULL = 1;
exports.ERROR_SESSION_DOES_NOT_EXIST = 2;
exports.ERROR_ROOM_DOES_NOT_EXIST = 3;
exports.ERROR_WRONG_PASSWORD= 4;
exports.ERROR_MISC = 5;
exports.ERROR_SAME_ROOM = 6;
